version: '3'
services:
  web:
    build: .
    command:  "sh ./run.sh" 
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://bard@postgres/story
      DEV: "true"
      POSTGRES_USER: bard
      POSTGRES_DB: story
      POSTGRES_PASSWORD: STORY
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: bard
      POSTGRES_DB: story
      POSTGRES_PASSWORD: STORY